name: Build and publish pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build script
      run: npm run build